import 'package:get/get.dart';

class MyTranslations implements Translations {
  @override
  // TODO: implement keys
  Map<String, Map<String, String>> get keys => {
        "ar": {
          'my_family': 'أسرتي',
          // TODO SPLASH
          'join_our_community': 'انضم إلى مجتمعنا',
          'already_member': 'عضوا فعلا؟',
          'login': 'تسجيل الدخول',
          'next': 'التالي',
          'skip': 'تخطي',

          'test_desc1': 'الأسرة تعني الكثير لمعظمنا. ترتبط العديد من العائلات بنوع معين من الحب لا يمكننا تجربته إلا ضمن إطار عائلي. إحدى الطرق التي يعبر بها أفراد الأسرة غالبًا عن حبهم لبعضهم البعض',
          'test_desc2': 'يمكن أن تكون مواكبة حركة الناس ، وخاصة المراهقين ، تحديًا شاقًا. لحسن الحظ ، أصبح هذا أسهل مع التكنولوجيا الحديثة المتقدمة. اليوم ، هناك تطبيقات لتتبع الأسرة.',
          'test_desc3': 'بصفتك أحد الوالدين ، يمكنك التبني من أجل سلامة أفراد أسرتك. أحد الأشياء الأساسية التي يمكنك القيام بها لتعزيز أمن أفراد عائلتك هو مراقبة تحركاتهم',

          // TODO LOGIN
          'family_name': 'إسم العائلة',
          'family_password': 'كلمة مرور العائلة',
          'confirm_password': 'تأكيد كلمة المرور',
          'enter_your_family_name': 'أدخل اسم عائلتك',
          'enter_password': 'ادخل كلمة المرور',
          'create_account': 'إنشاء حساب',
          'dont_have_account': 'ليس لديك حساب؟',
          'have_account': 'لدي حساب بالفعل',
          'create_new_family_password': 'أنشئ كلمة مرور جديدة للعائلة',
          'new_password_different_used_passwords': 'يجب أن تكون كلمة مرورك الجديدة مختلفة \n عن كلمات المرور المستخدمة سابقاً.',
          'New_Password': 'كلمة المرور الجديدة',
          'confirm_pass': 'تأكيد كلمة المرور',
          'both_passwords_must_match': 'يجب أن تتطابق كلمتا المرور.',
          'family_username': 'اسم مستخدم العائلة',
          'create_new_family_username': 'أنشئ اسم مستخدم جديد للعائلة',
          'new_family_username': 'اسم مستخدم جديد للعائلة',
          'khalil': 'خليل',
          'add_new_members': 'أضف أعضاء جدد',
          'member_type': 'نوع العضو :',
          'children': 'أطفال',
          'email_address': 'عنوان البريد الإلكتروني',
          'email': 'بريد إلكتروني',
          'permissions': 'أذونات',


          // TODO CREATE ACCOUNT
          'create_an_account': 'انشئ حساب',
          'connect_with_family_today': 'تواصل مع عائلتك اليوم!',
          'name': 'الإسم',
          'enter_your_name': 'أدخل أسمك',
          'email_address': 'عنوان البريد الإلكتروني',
          'enter_your_email': 'أدخل بريدك الإلكتروني',
          'password': 'كلمة المرور',
          'enter_Your_password': 'ادخل رقمك السري',
          'parents': 'الوالدين',
          'other_parent_email': 'البريد الإلكتروني الآخر للوالد',
          'optional': '(إختياري)',
          'helpers': 'المساعدين',
          'how_many_helpers': 'كم عدد المساعدين؟',
          'children': 'الأطفال',
          'how_many_children': 'كم طفل؟',
          'permissions': 'الصلاحيات',
          'admin': 'المسؤل',
          // TODO PERSONAL INFO
          'verify_personal_data': 'تحقق من البيانات الشخصية',
          'please_enter_your_name': 'من فضلك أدخل إسمك',
          'please_enter_your_email': 'رجاءا أدخل بريدك الإلكتروني',
          'please_enter_valid_email': 'الرجاء إدخال بريد إلكتروني صحيح',
          'please_enter_password': 'الرجاء إدخال كلمة المرور',
          'password_6_characters': 'يجب أن تكون كلمة المرور أكثر من 6 أحرف',
          // TODO FAMILY INFO
          'verify_family_data': 'تحقق من بيانات العائلة',
          'please_enter_your_family_name': 'الرجاء إدخال اسم عائلتك',
          'please_enter_your_family_password': 'الرجاء إدخال كلمة مرور عائلتك',
          'please_enter_confirm_password': 'الرجاء إدخال تأكيد كلمة المرور',
          'passwords_not_match': 'كلمتا المرور غير مطابقة',
          // TODO HELPER INFO
          'verify_helpers_data': 'تحقق من بيانات المساعدين',
          'please_enter_first_helper_email': 'الرجاء إدخال البريد الإلكتروني للمساعد الأول',
          'please_select_first_helper_permissions': 'الرجاء تحديد أذونات المساعد الأول',
          'please_enter_second_helper_email': 'الرجاء إدخال البريد الإلكتروني للمساعد الثاني',
          'please_select_second_helper_permissions': 'الرجاء تحديد أذونات المساعد الثاني',
          'please_enter_third_helper_email': 'الرجاء إدخال البريد الإلكتروني للمساعد الثالث',
          'please_select_third_helper_permissions': 'الرجاء تحديد أذونات المساعد الثالث',
          'please_enter_fourth_helper_email': 'الرجاء إدخال البريد الإلكتروني للمساعد الرابع',
          'please_select_fourth_helper_permissions': 'الرجاء تحديد أذونات المساعد الرابع',
          'must_select_one_helper': 'يجب اختيار مساعد واحد على الأقل',
          // TODO CHILD INFO
          'verify_children_data': 'تحقق من بيانات الأطفال',
          'please_enter_first_child_email': 'الرجاء إدخال البريد الإلكتروني للطفل الأول',
          'please_enter_second_child_email': 'الرجاء إدخال البريد الإلكتروني للطفل الثاني',
          'please_enter_third_child_email': 'الرجاء إدخال البريد الإلكتروني للطفل الثالث',
          'please_enter_fourth_child_email': 'الرجاء إدخال البريد الإلكتروني للطفل الرابع',
          'please_enter_fivth_child_email': 'الرجاء إدخال البريد الإلكتروني للطفل الخامس',
          'please_enter_sixth_child_email': 'الرجاء إدخال البريد الإلكتروني للطفل السادس',
          'please_enter_sevnth_child_email': 'الرجاء إدخال البريد الإلكتروني للطفل السابع',
          'please_enter_eighth_child_email': 'الرجاء إدخال البريد الإلكتروني للطفل الثامن',
          'must_select_one_child': 'يجب اختيار طفل واحد على الأقل',

          // TODO HOME
          'home': 'الرئيسية',
          'calendar': 'التقويم',
          'messages': 'الرسائل',
          'family': 'العائلة',
          'entertainment': 'الترفيه',
          'study': 'المذاكرة',
          'to_do_list': 'عمل قائمة',
          'add_entertainment': 'أضف ترفيه',
          'add_title_entertainment': 'أضف عنوانًا لعطلة نهاية الأسبوع هذه للترفيه' ,
          'add_title': 'أضف عنوانا',
          'add_suggestions': 'إضافة اقتراحات؟',
          'subjects': 'المواضيع',
          'add_study': 'أضف دراسة',
          'choose-child_assignment': 'اختر الطفل الذي يجب أن يسلم المهمة',
          'how_many_subjects': 'كم عدد المواضيع؟',
          'add_title_Subject': 'أضف عنوان الموضوع',
          'name_child': 'Name of Child',
          'send': 'رسال',
          'assignment': 'تكليف',
          'search_assignment': 'مهمة البحث',

          // TODO Entertainments
          'done': 'تم',
          'add_suggestion': 'أضف اقتراحًا',
          'enter_entertainment': 'الرجاء إدخال الترفيه',
          'choose_suggestion': 'الرجاء تحديد الاقتراحات',
          'suggestion': 'اقتراح',
          'please_enter_suggestion': 'الرجاء إدخال الاقتراح',
          'select_image': 'الرجاء إختار صورة',


          //TODO CHAT
          'create_group': 'إنشاء مجموعة',
          'group_name': 'أسم المجموعة',
          'participants': 'مشاركون :',
          'description': 'وصف',
          'of': 'الى',
          'choose_an_avatar_for_family_group': 'اختر صورة رمزية لمجموعة العائلة',
          'save': 'حفظ',
          'family_members': 'أفراد الأسرة',
          'search': 'البحث',



          // TODO MESSAGES
          'groups': 'مجموعات',

          // TODO SETTINGS
          'settings': 'الإعدادات',
          'edit_account': 'تعديل الحساب',
          'themes': 'لون التطبيق',
          'language': 'اللغة',
          'arabic': 'العربية',
          'english': 'الإنجليزية',
          'about': 'عن التطبيق',
          'help': 'مساعدة',
          'logout': 'تسجيل الخروج',
          'cancel': 'إلغاء',
          'notifications': ' الاشعارات',
          'explanation_of_the_problem': ' شرح المشكلة',
          'problem_title': 'عنوان المشكلة ',
          'enter_des_problem': 'أدخل وصفا للمشكلة',
          'Add_picture_problem': 'أضف صورة للمشكلة',
          "please_login": "الرجاء تسجيل الدخول أولاً للمتابعة \n لأنك الآن في وضع الضيف",
          'text_log_out': 'هل أنت متأكد من عملية \nالخروج من التطبيق',
          'no_data': 'لا يوجد بيانات حالياً',
        },
        "en": {
          'my_family': 'My Family',
          // TODO SPLASH
          'join_our_community': 'Join our community',
          'already_member': 'Already a member?',
          'login': 'Login',
          'next': 'Next',
          'skip': 'Skip',

          'test_desc1': 'Family means a lot to most of us. Many families are bound by a particular type of love that we can only experience within a family setup. One of the ways that family members often express their love for one another',
          'test_desc2': 'Keeping up with the movement of people, especially teenagers, can be quite a daunting challenge. Fortunately, this has been made easier with advanced modern technology. Today, there are family tracking apps.',
          'test_desc3': 'as a parent, you can adopt for the safety of your family members. One of the essential things that you can do to enhance the security of your family members is to monitor their movements',

          // TODO LOGIN
          'family_name': 'Family Name',
          'family_password': 'Family Password',
          'confirm_password': '​Confirm Password',
          'enter_your_family_name': 'Enter Your Family Name',
          'enter_password': 'Enter password',
          'create_account': 'Create account',
          'dont_have_account': 'Don\'t have an account?',
          'have_account': 'I already have an account',
          'create_new_family_password': 'Create new family password',
          'new_password_different_used_passwords': 'your new password must the different \n form previous used passwords.',
          'New_Password': 'New Password',
          'confirm_pass': 'Confirm Password',
          'both_passwords_must_match': 'Both passwords must match.',
          'family_username': 'Family Username',
          'create_new_family_username': 'Create new family username',
          'new_family_username': 'New family username',
          'thabet': 'Thabet',
          'add_new_members': 'Add new members',
          'member_type': 'member type :',
          'children': 'Children',
          'email_address': 'Email Address',
          'email': 'email',
          'permissions': 'Permissions',


          // TODO CREATE ACCOUNT
          'create_an_account': 'Create an account',
          'connect_with_family_today': 'Connect with your family today !',
          'name': 'Name',
          'enter_your_name': 'Enter your name',
          'email_address': 'Email​ Address',
          'enter_your_email': 'Enter your email',
          'password': 'Password',
          'enter_Your_password': 'Enter Your Password',
          'parents': 'Parents',
          'other_parent_email': 'The other parent email',
          'optional': '(optional)',
          'helpers': 'Helpers',
          'how_many_helpers': 'How many helpers?',
          'children': 'children',
          'how_many_children': 'How many children?',
          'permissions': 'Permissions',
          'admin': 'Admin',
          // TODO PERSONAL INFO
          'verify_personal_data': 'Verify personal data',
          'please_enter_your_name': 'Please enter your name',
          'please_enter_your_email': 'Please enter your email',
          'please_enter_valid_email': 'please enter a working email address',
          'please_enter_password': 'Please enter password',
          'password_6_characters': 'Password must be more than 6 characters long',
          // TODO FAMILY INFO
          'verify_family_data': 'Verify family data',
          'please_enter_your_family_name': 'Please enter your family name',
          'please_enter_your_family_password': 'Please enter your family password',
          'please_enter_confirm_password': 'Please enter confirm password',
          'passwords_not_match': 'Passwords do not match',
          // TODO HELPER INFO
          'verify_helpers_data': 'Verify helpers data',
          'please_enter_first_helper_email': 'Please enter the email of the first assistant',
          'please_select_first_helper_permissions': 'Please select first helper permissions',
          'please_enter_second_helper_email': 'Please enter the email of the second assistant',
          'please_select_second_helper_permissions': 'Please select second helper permissions',
          'please_enter_third_helper_email': 'Please enter the email of the third assistant',
          'please_select_third_helper_permissions': 'Please select third helper permissions',
          'please_enter_fourth_helper_email': 'Please enter the email of the fourth assistant',
          'please_select_fourth_helper_permissions': 'Please select fourth helper permissions',
          'must_select_one_helper': 'At least one assistant must be selected',
          // TODO ChILD INFO
          'verify_chidren_data': 'Verify children data',
          'please_enter_first_child_email': 'Please enter the email of the first child',
          'please_enter_second_child_email': 'Please enter the email of the second child',
          'please_enter_third_child_email': 'Please enter the email of the third child',
          'please_enter_fourth_child_email': 'Please enter the email of the fourth child',
          'please_enter_fivth_child_email': 'Please enter the email of the fivth child',
          'please_enter_sixth_child_email': 'Please enter the email of the sixth child',
          'please_enter_sevnth_child_email': 'Please enter the email of the sevnth child',
          'please_enter_eighth_child_email': 'Please enter the email of the eighth child',
          'must_select_one_child': 'At least one child must be selected',



          // TODO HOME
          'home': 'Home',
          'calendar': 'Calendar',
          'messages': 'Messages',
          'family': 'Family',
          'entertainment': 'Entertainment',
          'study': 'Study',
          'to_do_list': 'To-Do List',
          'add_entertainment': 'Add Entertainment',
          'add_title_entertainment': 'Add Title for this weekend,s Entertainment' ,
          'add_title': 'Add Title',
          'add_suggestions': 'Add suggestions?',
          'subjects': 'Subjects',
          'add_study': 'Add Study',
          'choose-child_assignment': 'Choose the child who has to hand over the \n assignment',
          'how_many_subjects': 'How many Subjects?',
          'add_title_Subject': 'Add Title of Subject',
          'name_child': 'Name of Child',
          'send': 'Send',
          'assignment': 'Assignment',
          'search_assignment': 'Search  assignment',


          // TODO Entertainments
          'done': 'Done',
          'add_suggestion': 'Add suggestion',
          'enter_entertainment': 'Please enter entertainment',
          'choose_suggestion': 'Please select suggestions',
          'suggestion': 'Suggestion',
          'please_enter_suggestion': 'Please enter suggestion',
          'select_image': 'Please select an image',

          //TODO CHAT
          'create_group': 'Create Group',
          'group_name': 'Group Name',
          'description': 'Description',
          'participants': 'PARTICIPANTS :',
          'of': '0F',
          'choose_an_avatar_for_family_group': 'Choose An Avatar For Family Group',
          'save': 'Save',
          'family_members': 'Family Members',
          'search': 'search',


          // TODO MESSAGES
          'groups': 'Groups',

          // TODO SETTINGS
          'settings': 'Settings',
          'edit_account': 'Edit account',
          'themes': 'Themes',
          'language': 'Language',
          'arabic': 'Arabic',
          'english': 'English',
          'about': 'About',
          'help': 'Help',
          'logout': 'Log out',
          'cancel': 'Cancel',
          'notifications': ' Notifications',
          'problem_title': 'Problem Title ',
          'enter_des_problem': 'Enter a description of the problem',
          'explanation_of_the_problem': ' Explanation of the problem',
          'Add_picture_problem': 'Add a picture of the problem',
          "please_login": "Please login first to continue \nBecause you are now in guest mode",
          'text_log_out': 'Are you sure about the checkout\n process  from the app',
          'no_data': 'There is no data currentlyً',

        },
      };
}
